### PR TITLE
Updated Flipkart.md

### PR DESCRIPTION
**Pull request by anjali1102**
@rishabh115 please review

### CODE REVIEW

**Review by rishabh115 — CHANGES_REQUESTED** [review]
Hi @anjali1102, there is quite conspicuous formatting issues. Please have a look at the contributing guidelines!

**Review by anjali1102 — COMMENTED** [review]
updated flipkart.md

**Review by rishabh115 — APPROVED** [review]
Thanks @anjali1102, Now everything looks the standard way. Please share this repo among your peers too.  I started this repo with an aim to organize the interview questions scattered throughout the internet in bits and pieces.

**Comment by anjali1102** [comment]
> Thanks @anjali1102, Now everything looks the standard way. Please share this repo among your peers too. I started this repo with an aim to organize the interview questions scattered throughout the internet in bits and pieces.

@

> Thanks @anjali1102, Now everything looks the standard way. Please share this repo among your peers too. I started this repo with an aim to organize the interview questions scattered throughout the internet in bits and pieces.

@rishabh115 kindly merge #103

**Pull request merged**
