### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by aru233**
Adding LinkedIn questions

### CODE REVIEW

**Review by rishabh115 — COMMENTED** [review]
Hi @aru233 , There are some formatting issues. Have a look at the contributing guidelines.

**Comment by aru233** [comment]
Hi @rishabh115, have fixed the formatting issues. Let me know if any more changes are needed.

**Comment by rishabh115** [comment]
> Hi @rishabh115, have fixed the formatting issues. Let me know if any more changes are needed.

There is one more issue in the last line. Please fix it and then it is ready to merge.

**Comment by aru233** [comment]
> > Hi @rishabh115, have fixed the formatting issues. Let me know if any more changes are needed.
> 
> There is one more issue in the last line. Please fix it and then it is ready to merge.

Fixed

**Review by rishabh115 — APPROVED** [review]
Thanks @aru233 , the commit looks good now. Please share the repo with your peers too. Happy Coding ✌️

**Pull request merged**
